### ISSUE TITLE
Typescript export errors

### ISSUE THREAD

**Issue by SoTrxII** [TooTallNate/node-speaker#142]
Hi there,
I've got some errors trying to build a project after including node-speaker as a dependency.
![image](https://user-images.githubusercontent.com/15107471/73591078-5c4fef80-44ea-11ea-9576-70fa7e5f82e5.png)

These can be resolved by using "export" on both the Speaker class and namespace, and by removing the exports = Speaker at the end of the `index.d.ts` file.

I've tested with Typescript 3.6.5 and 3.7.5 so far, on two separate projects.

As I'm not yet 100% sure this has nothing to do with my current TS config, I've not uploaded any PR yet.

**Comment by 89netraM** [comment]
I also encountered this problem, but I "solved" it by changing the last line to `export = Speaker`. I thought this made more sense since `index.js` exports `Speaker` as a default.

**Comment by TooTallNate** [comment]
Fixed in `v0.5.2`.

**Comment by cjheath** [comment]
I still have this problem in v0.5.2.
PR sent. Please fix this one way or another :)
